// Mocks generated by Mockito 5.0.17 from annotations
// in new_york_times_books/test/fetch_books_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:new_york_times_books/BLoC/best_seller_bloc.dart' as _i4;
import 'package:new_york_times_books/Models/book.dart' as _i3;
import 'package:new_york_times_books/Models/books_response.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeBooksResponse_0 extends _i1.Fake implements _i2.BooksResponse {}

/// A class which mocks [BooksResponse].
///
/// See the documentation for Mockito's code generation for more information.
class MockBooksResponse extends _i1.Mock implements _i2.BooksResponse {
  MockBooksResponse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i3.Book> get results => (super.noSuchMethod(Invocation.getter(#results),
      returnValue: <_i3.Book>[]) as List<_i3.Book>);
}

/// A class which mocks [BestSellersBloc].
///
/// See the documentation for Mockito's code generation for more information.
class MockBestSellersBloc extends _i1.Mock implements _i4.BestSellersBloc {
  MockBestSellersBloc() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i3.Book>> get booksStream =>
      (super.noSuchMethod(Invocation.getter(#booksStream),
              returnValue: Stream<List<_i3.Book>>.empty())
          as _i5.Stream<List<_i3.Book>>);
  @override
  void dispose() => super.noSuchMethod(Invocation.method(#dispose, []),
      returnValueForMissingStub: null);
  @override
  void getBestSellers(String? date) =>
      super.noSuchMethod(Invocation.method(#getBestSellers, [date]),
          returnValueForMissingStub: null);
  @override
  _i2.BooksResponse getBestSellersMethod(String? date) =>
      (super.noSuchMethod(Invocation.method(#getBestSellersMethod, [date]),
          returnValue: _FakeBooksResponse_0()) as _i2.BooksResponse);
}
